apiVersion: v1
kind: ConfigMap
metadata:
  name: bookservice-config
  namespace: bookservice
data:
  MYSQL_HOST: "mysql"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "bookdb"
  MYSQL_USER: "bookuser"
  DEPLOYMENT_TYPE: "kubernetes"
