apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: bookservice
type: Opaque
data:
  # Base64 encoded values
  # echo -n 'rootpassword' | base64
  mysql-root-password: cm9vdHBhc3N3b3Jk
  # echo -n 'bookpass' | base64
  mysql-password: Ym9va3Bhc3M=
