apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bookservice.fullname" . }}-config
  labels:
    {{- include "bookservice.labels" . | nindent 4 }}
data:
  MYSQL_HOST: {{ .Values.config.mysql.host | quote }}
  MYSQL_PORT: {{ .Values.config.mysql.port | quote }}
  MYSQL_DATABASE: {{ .Values.config.mysql.database | quote }}
  MYSQL_USER: {{ .Values.config.mysql.user | quote }}
