apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bookservice.fullname" . }}-secret
  labels:
    {{- include "bookservice.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-password: {{ .Values.mysql.auth.password | b64enc | quote }}
